======================================
# Bagian 1: Operasi Matematika Dasar dengan Python
======================================

In [ ]:
print("=== Operasi Matematika Dasar dengan Python ===")
a, b = 6, 2  # Contoh variabel
print(f"Penjumlahan ({a} + {b}):", a + b)
print(f"Pengurangan ({a} - {b}):", a - b)
print(f"Perkalian ({a} * {b}):", a * b)
print(f"Pembagian ({a} / {b}):", a / b)
print(f"Pangkat ({a} ** {b}):", a ** b)
print(f"Modulus ({a} % {b}):", a % b)
print(f"Pembagian Bulat ({a} // {b}):", a // b)


=== Operasi Matematika Dasar dengan Python ===
Penjumlahan (6 + 2): 8
Pengurangan (6 - 2): 4
Perkalian (6 * 2): 12
Pembagian (6 / 2): 3.0
Pangkat (6 ** 2): 36
Modulus (6 % 2): 0
Pembagian Bulat (6 // 2): 3


# Numpy

 ======================================
# Bagian 2: Mengenal Library Numpy
 ======================================

## Array

In [ ]:
import numpy as np

print("\n=== Pengenalan Library Numpy ===")

# Membuat Array 1D dan 2D
array_1d = np.array([1, 2, 3, 4])
array_2d = np.array([[1, 2], [3, 4]])
print("Array 1D:", array_1d)
print("Array 2D:\n", array_2d)



=== Pengenalan Library Numpy ===
Array 1D: [1 2 3 4]
Array 2D:
 [[1 2]
 [3 4]]


## Arrange dan linspace

In [ ]:
# Operasi dengan Numpy
print("\n=== Operasi dengan Numpy ===")
print("np.arange(0, 10, 2):", np.arange(0, 10, 2))
print("np.linspace(0, 1, 5):", np.linspace(0, 1, 5))
reshaped_array = np.arange(6).reshape(2, 3)
print("np.reshape():\n", reshaped_array)



=== Operasi dengan Numpy ===
np.arange(0, 10, 2): [0 2 4 6 8]
np.linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]
np.reshape():
 [[0 1 2]
 [3 4 5]]


## statistik numpy

In [ ]:
# Statistik
array = np.array([1, 2, 3, 4, 5])
print("\nStatistik dengan Numpy:")
print("Mean:", np.mean(array))
print("Median:", np.median(array))
print("Standar Deviasi:", np.std(array))


Statistik dengan Numpy:
Mean: 3.0
Median: 3.0
Standar Deviasi: 1.4142135623730951


# Pandas

 ======================================
# Bagian 3: Mengenal Library Pandas
 ======================================

In [ ]:
import pandas as pd

print("\n=== Pengenalan Library Pandas ===")

# Membuat DataFrame Sederhana
data = {
    "Nama": ["Isvi", "Nisa", "Nawa", "Dekhsa","ulil","zayga"],
    "Nilai": [85, 90, 78, 92, 87, 80],
    "Kelas": ["A", "B", "A", "B", "A", "B"]
}
df = pd.DataFrame(data)
print("DataFrame:\n", df)


=== Pengenalan Library Pandas ===
DataFrame:
      Nama  Nilai Kelas
0    Isvi     85     A
1    Nisa     90     B
2    Nawa     78     A
3  Dekhsa     92     B
4    ulil     87     A
5   zayga     80     B


## Operasi dengan Pandas

In [ ]:
# Operasi dengan Pandas
print("\n=== Operasi dengan Pandas ===")
print("Menampilkan 3 Baris Pertama:")
print(df.head(3))


=== Operasi dengan Pandas ===
Menampilkan 3 Baris Pertama:
   Nama  Nilai Kelas
0  Isvi     85     A
1  Nisa     90     B
2  Nawa     78     A


## Deskripsi Statistik

In [ ]:
print("\nDeskripsi Statistik:")
df.describe()


Deskripsi Statistik:


Nilai
count   6.000000
mean   85.333333
std     5.501515
min    78.000000
25%    81.250000
50%    86.000000
75%    89.250000
max    92.000000

## Grouping dan Agregasi

In [ ]:
# Grouping dan Agregasi
print("\nMengelompokkan Data Berdasarkan 'Kelas':")
print(df.groupby("Kelas")["Nilai"].mean())


Mengelompokkan Data Berdasarkan 'Kelas':
Kelas
A    83.333333
B    87.333333
Name: Nilai, dtype: float64


## Mengecek dan Mengisi Data Kosong

In [ ]:
# Mengecek dan Mengisi Data Kosong
df_with_nan = df.copy()
df_with_nan.loc[2, "Nilai"] = None  # Menambahkan nilai NaN
print("\nData dengan Nilai Kosong:\n", df_with_nan)
print("Cek Nilai Kosong:\n", df_with_nan.isnull())
print("\nMengisi Nilai Kosong dengan 0:")
df_with_nan.fillna(0, inplace=True)
print(df_with_nan)


Data dengan Nilai Kosong:
      Nama  Nilai Kelas
0    Isvi   85.0     A
1    Nisa   90.0     B
2    Nawa    NaN     A
3  Dekhsa   92.0     B
4    ulil   87.0     A
5   zayga   80.0     B
Cek Nilai Kosong:
     Nama  Nilai  Kelas
0  False  False  False
1  False  False  False
2  False   True  False
3  False  False  False
4  False  False  False
5  False  False  False

Mengisi Nilai Kosong dengan 0:
     Nama  Nilai Kelas
0    Isvi   85.0     A
1    Nisa   90.0     B
2    Nawa    0.0     A
3  Dekhsa   92.0     B
4    ulil   87.0     A
5   zayga   80.0     B


 ======================================
# Bagian 4: Contoh Implementasi untuk Data Science
 ======================================

## Membaca File CSV

In [ ]:
print("\n=== Contoh Implementasi Data Science ===")


# Pastikan untuk mengunggah file CSV di Google Colab sebelum menjalankan ini.
# Anda dapat menggunakan file contoh: https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv

from google.colab import files
uploaded = files.upload()  # Mengunggah file CSV

# Membaca file yang diunggah
file_name = list(uploaded.keys())[0]
df_csv = pd.read_csv(file_name)


=== Contoh Implementasi Data Science ===


Saving hw_200.csv to hw_200.csv


## Menampilkan 5 baris pertama

In [ ]:
print("\nData dari File CSV:")
print(df_csv.head())


Data dari File CSV:
   Index   Height(Inches)"   "Weight(Pounds)"
0      1             65.78             112.99
1      2             71.52             136.49
2      3             69.40             153.03
3      4             68.22             142.34
4      5             67.79             144.30


## Menganalisis data

In [ ]:

print("\nRingkasan Statistik Data CSV:")
print(df_csv.describe())


Ringkasan Statistik Data CSV:
            Index   Height(Inches)"   "Weight(Pounds)"
count  200.000000        200.000000         200.000000
mean   100.500000         67.949800         127.221950
std     57.879185          1.940363          11.960959
min      1.000000         63.430000          97.900000
25%     50.750000         66.522500         119.895000
50%    100.500000         67.935000         127.875000
75%    150.250000         69.202500         136.097500
max    200.000000         73.900000         158.960000


# Studi Kasus

 =====================================
# Bagian 5: Membuat Dataset Penjualan
 =====================================

In [ ]:
products = ["Produk A", "Produk B", "Produk C", "Produk D", "Produk E"]

months = ["Januari", "Februari", "Maret", "April", "Mei", "Juni",
          "Juli", "Agustus", "September", "Oktober", "November", "Desember"]

np.random.seed(42)
data = {
    "Bulan": np.tile(months, len(products)), # mengulang array sebanyak banyaknya produk
    "Produk": np.repeat(products, len(months)), # mengulang setiap elemen dalam array sejumlah banyaknya bulan
    "Jumlah Terjual (unit)": np.random.randint(50, 200, size=len(products) * len(months)),
    "Harga per Unit (Rp)": np.random.randint(10000, 50000, size=len(products) * len(months))
}

# Membuat DataFrame
df_sales = pd.DataFrame(data)

## Menampilkan 10 baris pertama

In [ ]:
# Menampilkan dataset
print("Dataset Penjualan:")
df_sales.head(10)

Dataset Penjualan:


Bulan    Produk  Jumlah Terjual (unit)  Harga per Unit (Rp)
0    Januari  Produk A                    152                19692
1   Februari  Produk A                    142                16873
2      Maret  Produk A                     64                15675
3      April  Produk A                    156                10161
4        Mei  Produk A                    121                47065
5       Juni  Produk A                     70                36557
6       Juli  Produk A                    152                43763
7    Agustus  Produk A                    171                42606
8  September  Produk A                    124                21534
9    Oktober  Produk A                    137                39127

## Menghitung total pendapatan

In [ ]:
df_sales["Total Pendapatan (Rp)"] = df_sales["Jumlah Terjual (unit)"] * df_sales["Harga per Unit (Rp)"]

In [ ]:
# Menampilkan dataset
print("Dataset Penjualan:")
df_sales.head(10) # Menampilkan 10 baris pertama

Dataset Penjualan:


Bulan    Produk  Jumlah Terjual (unit)  Harga per Unit (Rp)  \
0    Januari  Produk A                    152                19692   
1   Februari  Produk A                    142                16873   
2      Maret  Produk A                     64                15675   
3      April  Produk A                    156                10161   
4        Mei  Produk A                    121                47065   
5       Juni  Produk A                     70                36557   
6       Juli  Produk A                    152                43763   
7    Agustus  Produk A                    171                42606   
8  September  Produk A                    124                21534   
9    Oktober  Produk A                    137                39127   

   Total Pendapatan (Rp)  
0                2993184  
1                2395966  
2                1003200  
3                1585116  
4                5694865  
5                2558990  
6                6651976  
7                7285626  
8                2670216  
9                5360399

 =====================================
# Bagian 6: Analisis Data
 =====================================

## 1. Total Pendapatan Tahunan

In [ ]:
total_pendapatan = df_sales["Total Pendapatan (Rp)"].sum()
print("Total Pendapatan Tahunan: Rp", total_pendapatan)

Total Pendapatan Tahunan: Rp 224914195


## 2. Produk Terlaris (berdasarkan total unit terjual)

In [ ]:
produk_terlaris = df_sales.groupby("Produk")["Jumlah Terjual (unit)"].sum().idxmax()
print("\nProduk Terlaris:", produk_terlaris)


Produk Terlaris: Produk A


## 3. Rata-rata Pendapatan per Bulan

In [ ]:
rata_rata_pendapatan = df_sales.groupby("Bulan")["Total Pendapatan (Rp)"].mean()
print("\nRata-rata Pendapatan per Bulan:")
print(rata_rata_pendapatan)


Rata-rata Pendapatan per Bulan:
Bulan
Agustus      6408126.2
April        2267423.6
Desember     4064504.0
Februari     4437206.4
Januari      3139936.6
Juli         3272650.8
Juni         2701931.2
Maret        3933804.2
Mei          3258280.2
November     3061928.8
Oktober      4545599.0
September    3891448.0
Name: Total Pendapatan (Rp), dtype: float64


## 4. Analisis Penjualan per Produk

In [ ]:
penjualan_per_produk = df_sales.groupby("Produk")[["Jumlah Terjual (unit)", "Total Pendapatan (Rp)"]].sum()
print("\nPenjualan per Produk:")
print(penjualan_per_produk)


Penjualan per Produk:
          Jumlah Terjual (unit)  Total Pendapatan (Rp)
Produk                                                
Produk A                   1604               45792188
Produk B                   1474               44423618
Produk C                   1400               44452809
Produk D                   1470               48957270
Produk E                   1352               41288310
